function [ax, leg_patch, leg_label] = ...
    plot_pattern(ind_data, avg_data, err_data, patterns, pattern, ...
    what_analysis, calc_type, err_type, focus_type, ...
    colour_uebersicht, plot_font, linewidth, mrksz, capsize, x_factor)

% function to create variations of the first plot

% pre allocation
leg_patch = [];
leg_label = string();

% Axis Adjustments
ax = gca;
hold on

if strcmp(what_analysis, 'Reaction Times')

    switch focus_type

        case 'Overall'
            % Concat RTs for All Test Numbers, Samples & Subject/Sessions
            y_vals = vertcat(ind_data{:, pattern, :, :});

        case 'Matches'
            % Concat RTs for All Samples & Subject/Sessions
            y_vals = vertcat(ind_data{:, pattern, :, 1});
    end

else    % Performance/Response Frequency
    y_vals = avg_data(pattern);
end

% Adjust x vals
x_vals = (ones(size(y_vals, 1), 1) * pattern) + x_factor;

% Plotting
if strcmp(what_analysis, 'Reaction Times')

    % Boxplot
    plot_pattern = ...
        boxchart(x_vals, y_vals, ...
        "BoxFaceColor", colour_uebersicht, ...
        "BoxEdgeColor", colour_uebersicht, ...
        "BoxFaceAlpha", 0.2, ...
        "BoxMedianLineColor", colour_uebersicht, ...
        "WhiskerLineColor", colour_uebersicht, ...
        "WhiskerLineStyle", "none", ...
        "LineWidth", linewidth, ...
        "MarkerStyle", "none");
    plot_pattern.BoxWidth = plot_pattern.BoxWidth / 3;

else    % Performance/Response Frequency

    % Mark Chance Level
    chance_colour = ax.GridAlpha;
    yline(0.5, ...
        "LineStyle", ":", ...
        "Alpha", chance_colour * 3, ...
        "LineWidth", linewidth, ...
        "Color", "k")

    % Plot Error
    err_plot = ...
        errorbar(x_vals, y_vals, ...
        err_data(1, pattern)', err_data(2, pattern)', ...
        "LineStyle", "none", ...
        "Color", colour_uebersicht, ...
        "LineWidth", linewidth, ...
        "CapSize", capsize, ...
        "MarkerSize", mrksz);

    % Plot Average
    plot_pattern = ...
        plot(x_vals, y_vals, ...
        "LineStyle", "none", ...
        "LineWidth", linewidth, ...
        "Marker", "o", ...
        "Color", colour_uebersicht, ...
        "MarkerFaceColor", colour_uebersicht, ...
        "MarkerEdgeColor", "none", ...
        "MarkerSize", mrksz);

    % Legend Adjustments
    leg_patch(1) = plot_pattern;
    leg_patch(2) = err_plot;
    leg_label(1) = calc_type;
    leg_label(2) = err_type;
end

end
