function fig = ...
    plot_c_g(diff_data, colours_pattern_diff, curr_experiments, what_analysis, ...
    who_analysis, numerosities, sample_idx, plot_font, plot_pos, ...
    linewidth, mrksz, capsize, jitterwidth, dot_alpha, marker_factor, ...
    comb_chunk)

% Function to Plot Chunking/Groupitizing Plot for Each Subject, Sample,
% Data Type

% Pre Allocation
leg_patch = [];
leg_label = string();

% Pre Definition
if comb_chunk
    labelings = {'Chunking'; 'Groupitizing'};
    jitter_dots = [-jitterwidth jitterwidth];
else
    labelings = {'P2 - P1'; 'P3 - P1'; 'P3 - P2'};
    jitter_dots = [-jitterwidth 0 jitterwidth];
end

% Create Figure
fig = figure();

% Axis Adjustments
ax = gca;
hold on

set(gca, "TickDir", "out")
axis padded
ax.YGrid = "on";    % plot horizontal grid lines
ax.Color = [1 1 1];     % set background colour to white
ax.XColor = "k";    % set colour of axis to black
ax.YColor = "k";    % set colour of axis to black
ax.FontWeight = "bold";
ax.XAxis.FontSize = plot_font;  % set fontsize of ticks
ax.YAxis.FontSize = plot_font;  % set fontsize of ticks
xlabel(ax, "Pattern", "FontWeight", "bold");    % set x-axis label
ax.XTickLabel = curr_experiments;
ax.XTickLabelRotation = 0;
ax.XLim = [.5 length(patterns) + .5];
ylabel(ax, ['Difference in ' what_analysis], "FontWeight", "bold")

% Mark 0 Line
chance_colour = ax.GridAlpha;
yline(0.5, ...
    "LineStyle", ":", ...
    "Alpha", chance_colour * 0.3, ...
    "LineWidth", linewidth, ...
    "Color", "k")

% Iterate over Experiments
for exp_idx = 1:length(curr_experiments)

    % set data
    curr_data = diff_data{exp_idx, sample_idx};
    ind_data = [curr_data{2, :}];
    avg_data = [curr_data{3, :}];
    err_data = [curr_data{4, :}];

    % iterate over amount of differences to be displayed
    for pattern = 1:length(labelings)
        
        %% Plot individual Dots
        % set y vals
        y_vals = ind_data(:, pattern);
        % set x vals
        x_vals = (ones(size(y_vals, 1)) * exp_idx) + jitter_dots(pattern);

        % Plot
        dot_plot = swarmchart(x_vals, y_vals, mrksz * marker_factor, ...
            "XJitter", "randn", ...
            "XJitterWidth", jitterwidth, ...
            "Marker", "o", ...
            "MarkerFaceColor", colours_pattern_diff{pattern}, ...
            "MarkerEdgeColor", "none", ...
            "MarkerFaceAlpha", dot_alpha);

        %% Plot Average
        plot_pattern = ...
            plot(exp_idx + jitter_dots(pattern), avg_data(pattern), ...
            "LineStyle", "none", ...
            "LineWidth", linewidth, ...
            "Marker", "o", ...
            "Color", colours_pattern_diff{pattern}, ...
            "MarkerFaceColor", colours_pattern_diff{pattern}, ...
            "MarkerEdgeColor", "none", ...
            "MarkerSize", mrksz);

        %% Plot Error
        err_plot = ...
            errorbar(exp_idx + jitter_dots(pattern), ...
            avg_data(pattern), err_data(pattern), err_data(pattern), ...
            "LineStyle", "none", ...
            "Color", colours_pattern_diff{pattern}, ...
            "LineWidth", linewidth, ...
            "CapSize", capsize, ...
            "MarkerSize", mkrsz);

        %% Legend Adjustments
        leg_patch(pattern) = plot_pattern;
        leg_label(pattern) = labelings{pattern};
    end
end

%% More Legend Adjustments
% plot invisible error plot
errr_plot = errorbar(0, 1, 5, 1, ...
    "LineStyle", "none", ...
    "Color", "k", ...
    "LineWidth", linewidth, ...
    "CapSize", capsize, ...
    "MarkerSize", mrksz, ...
    "Marker", "o", ...
    "MarkerEdgeColor", "none", ...
    "MarkerFaceColor", "k");

leg_patch(end + 1) = errr_plot;
leg_label(end + 1) = err_type;

%% Figure Adjustments
fig_title = title([calc_type ' Difference in ' what_analysis ' of ' ...
    who_analysis ' for Sample ' num2str(numerosities(sample_idx, 1))]); 
[fig_pretty, ~] = ...
    prettify_plot(fig, plot_pos, fig_title, plot_font, ...
    true, leg_patch, leg_label, ' ', mrksz, ax);

end